### ISSUE TITLE
Have a chat bot that can answer customers' frequently asked questions

### ISSUE THREAD

**Issue by pphaoniubi** [pphaoniubi/SOEN-341-Shopping-Web#104]
**Description:**
Have a chat bot that can answer customers' frequently asked questions

**Risk:** 
Medium, a chat bot should not be too complicated to implement. 

**Priority:** 
Medium. This feature can clear customers' confusion, therefore can be useful from time to time.

**Story Point:**
5

**Priority:**
High

**Related Epic User Story:**
N/A

**Related Task:**
N/A

**Comment by paullmq8** [comment]
won't complete this feature.
