### ISSUE TITLE
Backend Techniques Discussion

### ISSUE THREAD

**Issue by paullmq8** [pphaoniubi/SOEN-341-Shopping-Web#5]
### Date and Time:  
2022.01.21  13:20 - 14:00

### Location: 
virtual meeting by WeChat

### Attendees:
Pai Peng and Mengqi Liu

### Notes:
We discussed about the techniques we will try to use in this project. Because some of our courses are about Java programming, we decide to use Java as our main coding language. And in Java ecosystem there's famous frameworks like Spring, Spring Boot, Spring Data JPA which will help us build backend microservices. Spring provides IOC mechanism to easily manage Java beans. Spring Boot helps us to build API endpoints. Spring Data JPA will support the database persistence layer. So these are the final techniques we decide to use in this project. Also for the database we choose the open source Postgres as our main data storage.

**Comment by pphaoniubi** [comment]
Notes said it all. The meeting concluded with all the technology we will be using to build the backend.
