### ISSUE TITLE
cannot register, exception thrown

### ISSUE THREAD

**Issue by pphaoniubi** [pphaoniubi/SOEN-341-Shopping-Web#73]
<img width="1579" alt="image" src="https://user-images.githubusercontent.com/85983149/155371879-c52e9b6b-0493-44f8-adee-4bf26ea20aa1.png">

<img width="1559" alt="image" src="https://user-images.githubusercontent.com/85983149/155371977-94cebc60-beb0-48c2-856c-5101be342449.png">

**Comment by paullmq8** [comment]
Issue is fixed. Account registration api is completed.
